=== Elentary/University/src/by/bsu/labs/lab14/xml/DataBase.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">

    <xs:element name="flowers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flower" type="Flower" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Flower">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="origin" type="xs:string" minOccurs="0"/>
            <xs:element name="soil" type="Soil" minOccurs="0"/>
            <xs:element name="visualParameters" type="VisualParameters" minOccurs="0"/>
            <xs:element name="growingTips" type="GrowingTips" minOccurs="0"/>
            <xs:element name="multiplying" type="Multiplying" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="GrowingTips">
        <xs:sequence>
            <xs:element name="temperature" type="xs:double" minOccurs="0"/>
            <xs:element name="light" type="xs:boolean" minOccurs="0"/>
            <xs:element name="watering" type="xs:int" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VisualParameters">
        <xs:sequence>
            <xs:element name="halm" type="Color" minOccurs="0"/>
            <xs:element name="leaf" type="Color" minOccurs="0"/>
            <xs:element name="meanSize" type="xs:double" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Soil">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ground"/>
            <xs:enumeration value="Podzol"/>
            <xs:enumeration value="SodPodzol"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Multiplying">
        <xs:restriction base="xs:string">
            <xs:enumeration value="byLeaves"/>
            <xs:enumeration value="bySeed"/>
            <xs:enumeration value="byCutting"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Color">
        <xs:restriction base="xs:string">
            <!--<xs:pattern value="^((([0-1][0-9]{2};)|(2[0-5][0-5]);)){3}$"/>-->
            <!--<xs:pattern value="^(([01][0-9][0-9]|2[0-4][0-9]|25[0-5]);){3}$"/>-->
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Elentary/University/src/by/bsu/labs/lab14/xml/DataBase.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE flowers [
        <!ELEMENT flowers (flower)*>
        <!ATTLIST flowers
                xmlns:xsi CDATA #REQUIRED
                xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
        <!ELEMENT flower (name|origin|soil|visualParameters|growingTips|multiplying)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT origin (#PCDATA)>
        <!ELEMENT soil (#PCDATA)>
        <!ELEMENT visualParameters (halm|leaf|meanSize)*>
        <!ELEMENT halm (#PCDATA)>
        <!ELEMENT leaf (#PCDATA)>
        <!ELEMENT meanSize (#PCDATA)>
        <!ELEMENT growingTips (temperature|light|watering)*>
        <!ELEMENT temperature (#PCDATA)>
        <!ELEMENT light (#PCDATA)>
        <!ELEMENT watering (#PCDATA)>
        <!ELEMENT multiplying (#PCDATA)>
        ]>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="DataBase.xsd">
    <flower>
        <name>Rose</name>
        <origin>Belarus</origin>
        <soil>Podzol</soil>
        <visualParameters>
            <halm>255;000;000;</halm>
            <leaf>000;255;000;</leaf>
            <meanSize>22.3</meanSize>
        </visualParameters>
        <growingTips>
            <temperature>26</temperature>
            <light>true</light>
            <watering>150</watering>
        </growingTips>
        <multiplying>byCutting</multiplying>
    </flower>
    <flower>
        <name>Daffodil</name>
        <origin>Netherlands</origin>
        <soil>Ground</soil>
        <visualParameters>
            <halm>255;000;120;</halm>
            <leaf>020;255;000;</leaf>
            <meanSize>17</meanSize>
        </visualParameters>
        <growingTips>
            <temperature>23</temperature>
            <light>true</light>
            <watering>230</watering>
        </growingTips>
        <multiplying>bySeed</multiplying>
    </flower>
    <flower>
        <name>Amarelis</name>
        <origin>Unknown</origin>
        <soil>SodPodzol</soil>
        <visualParameters>
            <halm>155;140;160;</halm>
            <leaf>120;255;000;</leaf>
            <meanSize>30.5</meanSize>
        </visualParameters>
        <growingTips>
            <temperature>28</temperature>
            <light>false</light>
            <watering>345</watering>
        </growingTips>
        <multiplying>byLeaves</multiplying>
    </flower>
</flowers>
